// Shopify embedded app (install/settings UI) + Web Pixel extension (SPEC §7.1, ADR-0008). This
// workspace path is a stub only — the real scaffold is generated by the official Shopify app
// template/CLI at M1-1, not hand-written here, per CLAUDE.md rule 7 (boring, documented tooling).

export function placeholder(): string {
  return 'apps/shopify-app not yet scaffolded (SPEC §12 M1-1)';
}
